config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :users do
    member do
      get "artworks", to: "feeds#artworks", feed_type: :created
      get "artwork_reblogs", to: "feeds#artwork_reblogs", feed_type: :created
      get "scraps", to: "feeds#scraps", feed_type: :created
      get "verify_email"
      get "unsubscribe"
      get "followers"
      get "mutuals"
    end
  end


  resources :sessions do
    collection do
      delete "logout"
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :scraps do
    concerns :commentable, commentable_type: "Scrap"
  end

  resources :artworks do
    concerns :commentable, commentable_type: "Artwork"
  end

  resources :followings, only: [:create, :destroy]

  resources :tags

  resources :artwork_reblogs

  resources :notifications, only: [:index, :show, :update, :destroy] do
    get "unread", on: :collection
  end

  scope "feeds" do
    get "/", to: "feeds#index"
    get "artworks", to: "feeds#artworks"
    get "scraps", to: "feeds#scraps"
    get "artwork_reblogs", to: "feeds#artwork_reblogs"
  end

  scope "sitemaps", defaults: { format: "txt" } do
    get "tags", to: "sitemaps#tags"
    get "users", to: "sitemaps#users"
    get "scraps", to: "sitemaps#scraps"
    get "artworks", to: "sitemaps#artworks"
    get "/", to: "sitemaps#index"
  end

  get "faq", to: "info_pages#faq"
  get "rules", to: "info_pages#rules"
  get "legal", to: "info_pages#legal"

  root to: "home#index"

end

app/models/user.rb
class User < ApplicationRecord
  include Paginated

  has_secure_password

  has_many :scraps

  has_many :scrap_comments

  has_many :artworks

  has_many :followee_followings,
    class_name: "Following",
    foreign_key: :followee_id
  has_many :users_following,
    through: :followee_followings,
    class_name: "User",
    source: :follower

  has_many :follower_followings,
    class_name: "Following",
    foreign_key: :follower_id

  has_many :users_followed,
    through: :follower_followings,
    class_name: "User",
    source: :followee 

  has_many :notifications

  # ATTACHMENTS
  has_one_attached :avatar

  # METAPROGRAMMING WEIRDNESS

  class NotificationPrefs
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :user_followed, :boolean
    attribute :user_commented, :boolean
    attribute :user_reblogged, :boolean

    def to_json
      attributes.to_json
    end

    class Type < ActiveRecord::Type::Value
      def type
        :jsonb
      end

      def cast value
        NotificationPrefs.new(value)
      end

      def deserialize value
        if String === value
          decoded = ::ActiveSupport::JSON.decode(value) rescue nil
          NotificationPrefs.new(decoded)
        else
          super
        end
      end

      def serialize value
        case value
        when Array, Hash
          ::ActiveSupport::JSON.encode(value)
        when NotificationPrefs
          value.to_json
        else
          super
        end
      end
    end
  end

  attribute :notification_email_prefs, NotificationPrefs::Type.new


  # TOKENS
  has_secure_token :email_confirmation_token
  has_secure_token :unsubscribe_token

  # VALIDATIONS
  validates :name, presence: true
  validates :email, presence: true

  # HOOKS
  after_create :verify_email!

  def unsubscribe_from_everything!
    attrs = notification_email_prefs.attributes.map do |k, v|
      [k, false]
    end
    regenerate_unsubscribe_token
    update(notification_email_prefs: Hash[attrs])
  end


  def mutuals
    User.where(id: users_following).where(id: users_followed)
  end

  def followed_by? user
    users_following.include? user
  end

  def following? user
    users_followed.include? user
  end

  def followable_by? user
    ! user.nil? && ! followed_by?(user)
  end

  def unfollowable_by? user
    ! user.nil? && followed_by?(user)
  end

  def avatar_img
    return avatar.variant(resize: "128x128>") if avatar.attachment
    "default_square.png"
  end

  def small_avatar_img
    return avatar&.variant(resize: "64x64>") if avatar.attachment
    "default_square.png"
  end

  def verify_email!(later = true)
    t = EmailValidatorMailer.with(user: self).verify_email
    if later
      t.deliver_later
    else
      t.deliver_now
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, only: 
    [:show, :edit, :update, :destroy, 
     :feed, :verify_email, :unsubscribe,
     :mutuals, :followers]

  def show
  end

  def feed
  end

  def mutuals
  end

  def followers
  end

  def verify_email
    token = params[:auth_token]
    if token != @user.email_confirmation_token
      redirect_to root_path
    elsif @user.update(email_confirmed: true)
      flash[:notice] = "Email confirmed!"
      redirect_to @user
    else
      redirect_to root_path
    end
  end

  def unsubscribe
    token = params[:unsubscribe_token]
    if token != @user.unsubscribe_token || token.nil?
      redirect_to root_path
    elsif @user.unsubscribe_from_everything!
      flash[:notice] = "Unsubscribed from all email notifications"
      redirect_to @user
    else
      redirect_to root_path
    end
  end

  def index 
    @users = paginate(policy_scope(User.all))
    authorize @users
  end  

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_create_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
        format.json { render @user }
      end
        format.html { render 'new' }
        format.json { render @user.errors }
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render @user }
      else
        format.html { render 'edit' }
        format.json { render @user.errors }
      end
    end
  end

  protected

  def user_create_params
    params
      .require(:user)
      .permit(:name, :email, :password, :password_confirmation)
  end

  def user_params
    params
      .require(:user)
      .permit(:bio, :avatar, prefs: [:nsfw],
              notification_email_prefs: notification_email_prefs_params)
  end

  def notification_email_prefs_params
    [:user_followed, :user_commented, :user_reblogged]
  end

  def load_user
    @user = policy_scope(User).find(params[:id])
    authorize @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def action_class act
    return "" if is_artwork_reblog_hack?
    if params[:action].to_s == act.to_s
      "is-active"
    else
      ""
    end
  end

  def artwork_reblog_class
    if params[:action].to_s == "artwork_reblogs" || is_artwork_reblog_hack?
      return "is-active"
    else
      return ""
    end
  end

  def is_artwork_reblog_hack?
    params[:controller].to_s == "artwork_reblogs"
  end

end

app/views/users/_artwork.html.erb
<div class="column is-one-quarter">
  <%= link_to artwork, class: "box centered-image-container" do -%>
    <%= image_tag artwork.image.variant(resize: "500x500>") %>
  <% end -%>
</div>

app/views/users/_bio_section.html.erb
<section class="section" itemscope itemtype="https://schema.org/Person">
  <div class="container">
    <div class="media">
      <figure class="media-left">
        <p class="image is-128x128">
          <%= image_tag @user.avatar_img, itemprop: "image" %>
        </p>
      </figure>
      <div class="media-content">
        <div class="content">
          <h1 class="title">
            <span itemprop="name"><%= @user.name %></span>
            <span> </span>
            <% if @user == current_user %>
              <%= link_to edit_user_path(@user), class: "material-icons" do %>
                <i class="material-icons">edit</i>
              <% end -%>
            <% end -%>
            <% if @user.followable_by? current_user -%>
              <%= form_for Following.new(followee: @user) do |f| %>
                <%= f.hidden_field :followee_id %>
                <%= f.submit "Follow", class: "button is-primary" %>
              <% end -%>
            <% end -%>
            <% if @user.unfollowable_by? current_user -%>
              <%= form_tag following_path(@user.id), method: :delete do -%>
                <%= submit_tag "Unfollow", class: "button is-danger" -%>
              <% end -%>
            <% end -%>
          </h1>
          <meta itemprop="description"
                content="<%= @user.bio %>" />
          <div class="text">
            <%= @user.bio %>
          </div>
        </div>
      </div>
    </div>
</section>

app/views/users/_form.html.erb
<%= form_for user, class: "form" do |f| %>
<div class="field">
<%= f.label :name, class: "label" %>
<div class="control">
<%= f.text_field :name, class: "input" %>
</div>
</div>

<div class="field">
<%= f.label :email, class: "label" %>
<div class="control">
<%= f.email_field :email, class: "input" %>
</div>
</div>

<div class="field">
<%= f.label :password, class: "label" %>
<div class="control">
<%= f.password_field :password, class: "input" %>
</div>
</div>

<div class="field">
<%= f.label :password_confirmation, class: "label" %>
<div class="control">
<%= f.password_field :password_confirmation, class: "input" %>
</div>
</div>


<%= f.submit class: "button" %>
<% end %>

app/views/users/_tabs.html.erb
<div class="tabs">
  <ul>
    <li class="<%= action_class :show %>">
      <%= link_to "Feed", user_path(@user) %>
    </li>
    <li class="<%= action_class :artworks %>">
      <%= link_to "Artworks", artworks_user_path(@user) %>
    </li>
    <li class="<%= action_class :scraps %>">
      <%= link_to "Scraps", scraps_user_path(@user) %>
    </li>
    <li class="<%= artwork_reblog_class %>">
      <%= link_to "Reblogs", artwork_reblogs_user_path(@user) %>
    </li>
    <li class="<%= action_class :followers %>">
      <%= link_to "Followers", followers_user_path(@user) %>
    </li>
    <% if policy(@user).mutuals? %>
      <li class="<%= action_class :mutuals %>">
        <%= link_to "Mutuals", mutuals_user_path(@user) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/_user.html.erb
<div class="card-spacer">
  <div class="card">
    <header class="card-header">
      <%= link_to user, class: "card-header-title" do -%>
        <%= user.name %>
      <% end -%>
    </header>

    <div class="card-content">
      <p>
        <%= user.bio %>
      </p>
    </div>
  </div>
</div>

app/views/users/artworks.html.erb
<%= render 'users/bio_section' %>
<%= page_title "#{@user.name} | Artworks" %>
<section class="section">
  <div class="container">
    <%= render "users/tabs" %>
    <div class="columns is-multiline">
      <%= render partial: "users/artwork",
          collection: policy_scope(@user.artworks),
          as: :artwork,
          cache: true %>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<div class="section">
  <%= form_for @user, class: "form" do |f| %>
    <div class="field">
      <%= f.label :bio, class: "label" %>
      <div class="control">
        <%= f.text_area :bio, class: "textarea" %>
      </div>
    </div>

    <div class="field">
      <div class="file">
        <%= f.label :avatar, class: "file-label" do %>
          <%= f.file_field :avatar, class: "file-input" %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="material-icons">upload</i>
            </span>
            <span class="file-label">
              Avatar
            </span>
          </span>
        <% end -%>
      </div>
    </div>

    <%= f.fields_for :prefs do |f| %>
      <div class="field">
        <%= f.label :nsfw, class: "label" %>
        <div class="select">
          <%= f.select :nsfw,
            [["Disabled", "disabled"], 
             ["Allowed", "allowed"],
             ["Required", "required"]],
          selected: @user.prefs["nsfw"] %>
        </div>
      </div>
    <% end %>

    <%= f.fields_for :notification_email_prefs,
        @user.notification_email_prefs do |ff| -%>
      <h2 class="subtitle">Notification Email Preferences</h2>
      <div class="field">
        <%= ff.label :user_followed, class: "checkbox" do %>
          <%= ff.check_box :user_followed %>
          New Followers
        <% end -%>
      </div>
      <div class="field">
        <%= ff.label :user_commented, class: "checkbox" do %>
          <%= ff.check_box :user_commented %>
          Comments on your Scraps and Artworks
        <% end -%>
      </div>
      <div class="field">
        <%= ff.label :user_reblogged, class: "checkbox" do %>
          <%= ff.check_box :user_reblogged %>
          Reblogs of your content
        <% end -%>
      </div>
    <% end -%>

    <div class="field">
      <%= f.submit class: "button" %>
    </div>
  <% end %>
</div>

app/views/users/feed.html.erb
<%= render 'bio_section' %>

<section class="section">
  <div class="container">
    <%= render 'tabs' %>
    
  <div data-vue-component="content-feed/base"
       data-base-url="<%= user_url @user %>">
  </div>
  </div>
</section>

app/views/users/followers.html.erb
<%= render 'bio_section' %>
<%= page_title "#{@user.name}'s followers" %>

<section class="section">
  <div class="container">
    <%= render 'tabs' %>
    <%= render @user.users_following %>
  </div>
</section>

app/views/users/index.html.erb
<% page_title "Users" %>

<section class="section">
  <div class="container">
    <h1 class="title">Users</h1>
    <%= render @users %>
    <%= render "page_level", collection: @users %>
  </div>
</section>

app/views/users/mutuals.html.erb
<%= render 'bio_section' %>
<%= page_title "#{@user.name}'s Mutuals" %>

<section class="section">
  <div class="container">
    <%= render "tabs" %>
    <%= render @user.mutuals %>
  </div>
</section>

app/views/users/new.html.erb
<div class="section">
  <%= render "form", user: @user %>
</div>

app/views/users/scraps.html.erb
<%= render "users/bio_section" %>
<%= page_title "#{@user.name} | Scraps" %>

<section class="section">
  <div class="container">
    <%= render "users/tabs" %>
    <div class="columns is-multiline">
      <%= render partial: "scraps/column_scrap", 
        collection: policy_scope(@user.scraps),
        as: :scrap,
        cache: true
      %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= render 'bio_section' %>
<%= page_title @user.name %>

<section class="section">
  <div class="container">
    <%= render 'tabs' %>
    
  <div data-vue-component="content-feed/base"
       data-base-url="<%= user_url @user %>">
  </div>
  </div>
</section>