config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :users do
    member do
      get "artworks", to: "feeds#artworks", feed_type: :created
      get "artwork_reblogs", to: "feeds#artwork_reblogs", feed_type: :created
      get "scraps", to: "feeds#scraps", feed_type: :created
      get "verify_email"
      get "unsubscribe"
      get "followers"
      get "mutuals"
    end
  end


  resources :sessions do
    collection do
      delete "logout"
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :scraps do
    concerns :commentable, commentable_type: "Scrap"
  end

  resources :artworks do
    concerns :commentable, commentable_type: "Artwork"
  end

  resources :followings, only: [:create, :destroy]

  resources :tags

  resources :artwork_reblogs

  resources :notifications, only: [:index, :show, :update, :destroy] do
    get "unread", on: :collection
  end

  scope "feeds" do
    get "/", to: "feeds#index"
    get "artworks", to: "feeds#artworks"
    get "scraps", to: "feeds#scraps"
    get "artwork_reblogs", to: "feeds#artwork_reblogs"
  end

  scope "sitemaps", defaults: { format: "txt" } do
    get "tags", to: "sitemaps#tags"
    get "users", to: "sitemaps#users"
    get "scraps", to: "sitemaps#scraps"
    get "artworks", to: "sitemaps#artworks"
    get "/", to: "sitemaps#index"
  end

  get "faq", to: "info_pages#faq"
  get "rules", to: "info_pages#rules"
  get "legal", to: "info_pages#legal"

  root to: "home#index"

end

app/models/scrap.rb
class Scrap < ApplicationRecord

  # CONCERNS
  include Worksafe
  include TagSearched
  include Searched
  include Feeded
  include Paginated

  # RELATIONS 
  belongs_to :user


  has_many :comments,
    class_name: "ScrapComment"

  has_many :scrap_tags
  has_many :tags, through: :scrap_tags

  # ATTACHMENTS 
  has_one_attached :image

  # VALIDATIONS
  validates :user, presence: true

  validates :image, attached: true


  # SCOPES
  def self.made_by users
    joins(:user).where(user: users)
  end

  # METHODS
  def thumbnail_path
    return image.variant(resize: "500x500>") if image.attachment
    "default_square.png"
  end

end

app/controllers/scraps_controller.rb
class ScrapsController < ApplicationController
  before_action :set_scrap,
    only: [:show, :edit, :update, :destroy]


  def index
    scraps = policy_scope(Scrap)
      .includes(image_attachment: :blob)
      .search(params[:search])
    @scraps = paginate(scraps)
    authorize @scraps
  end

  def new
    @scrap = Scrap.new
    authorize @scrap
  end

  def create
    @scrap = Scrap.new(scrap_params)
    authorize @scrap
    respond_to do |format|
      if @scrap.save
        format.html { redirect_to @scrap }
        format.json { render @scrap }
      else
        format.html { render 'new' }
        format.json { render @scrap.errors }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @scrap.update(scrap_params)
        format.html { redirect_to @scrap }
        format.json { render @scrap }
      else
        format.html { render "new", status: 401 }
        format.json { render @scrap.errors, status: 401 }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @scrap.destroy 
        format.html { redirect_to scraps_path }
      else
        format.html { redirect_to @scrap }
      end
    end
  end

  protected

  def scrap_params
    params
      .require(:scrap)
      .permit(:image, :name, :description, :nsfw, tag_ids: [])
      .merge(user: current_user)
  end

  def set_scrap
    @scrap = Scrap.find(params[:id])
    authorize @scrap
  end

end

app/helpers/scraps_helper.rb
module ScrapsHelper
end

app/views/scraps/_column_scrap.html.erb
<div class="column is-one-quarter">
  <%= link_to scrap, class: "box centered-image-container" do %>
    <%= image_tag scrap.thumbnail_path %>
  <% end -%>
</div>

app/views/scraps/_form.html.erb
<%= form_for @scrap, class: "form" do |f| %>

  <div class="centered-image-container">
    <% if @scrap.image.attachment %>
      <%= image_tag @scrap.image.variant(resize: "1000x1000<"), id: "uploadPreview" %>
    <% else %>
      <%= image_tag "placeholder_img.svg", id: "uploadPreview" %>
    <% end %>
  </div>
  <div class="field">
    <div class="file is-boxed is-centered has-name">
      <%= f.label :image, class: "file-label" do %>
        <%= f.file_field :image, 
          class: "file-input is-previewed-file",
          data: { "file-preview-container": "uploadPreview" } %>
        <span class="file-cta">
          <span class="file-label">
            Choose a file…
          </span>
        </span>
        <span class="file-name">
        </span>
      <% end %>
    </div>
  </div>


  <div class="field">
    <%= f.label :name, "Name (Optional)" %>
    <div class="control">
      <%= f.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :descrption, "Description (Optional)" %>
    <div class="control">
      <%= f.text_area :description, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :nsfw do %>
      <%= f.check_box :nsfw %>
      NSFW?
    <% end %>
  </div>

  <div class="field">
    <div data-vue-component="tags/new-tags-form"
         data-field-name="scrap[tag_ids]"
         <% if @scrap.persisted? %>
           data-field-preload-url="<%= url_for @scrap %>"
         <% end %>
         data-field-preload-path="tags"
         data-allow-create="true">
    </div>
  </div>


  <%= f.submit class: "button" %>

<% end %>

app/views/scraps/_scrap.html.erb
<%= link_to scrap, class: "scrap-image-container" do %>
  <%= image_tag scrap.image.variant(resize: "500x500>") %>
<% end -%>

app/views/scraps/edit.html.erb
<% page_title "Editing \"#{@scrap.name || "Untitled"}\"" %>

<div class="section">
  <%= render "form" %>
</div>

app/views/scraps/index.html.erb
<% page_title "Scraps" %>

<div class="section">
  <div class="container">
    <h1 class="title">Scraps</h1>
    <%= form_tag scraps_path, method: :get, class: "form" do %>

      <div class="field">
        <label for="search[tags]" class="label">Tags</label>
        <div data-vue-component="tags/new-tags-form"
             data-field-name="search[tags]">
        </div>
      </div>
      <%= submit_tag "Search", class: "button" %>
    <% end %>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="columns is-multiline">
      <%= render collection: @scraps,
        partial: "column_scrap",
        cached: true,
        as: :scrap %>
    </div>
    <%= render "page_level", collection: @scraps %>
  </div>
</div>

app/views/scraps/new.html.erb
<% page_title "New Scrap" %>

<div class="section">
  <%= render "form" %>
</div>

app/views/scraps/show.html.erb
<% page_title "\"#{@scrap.name || "Untitled"}\" by #{@scrap.user.name}" %>
<% meta_tag :description, @scrap.description %>
<% meta_tag :keywords, tags_to_keywords(@scrap.tags) %>
<% og_tag(:image, 
  polymorphic_url(@scrap.image.variant(resize: "1000x1000>"))) %>
<% og_tag :image_alt, @scrap.description %>
<div itemscope itemtype="https://schema.org/VisualArtwork">   
  <div class="section">
    <div class="container">
      <div class="card">
        <%= link_to url_for(@scrap.image),
          itemprop: "image",
          class: "card-image centered-image-container" do %>
          <%= image_tag @scrap.image.variant(resize: "1000x1000>") %>
        <% end %>

        <div class="card-content">
          <div class="content">
            <p class="title">
              <span itemprop="headline">
                <% if @scrap.name.blank? %>
                  Untitled
                <% else %>
                  <%= @scrap.name %>
                <% end -%>
              </span>
              <% if policy(@scrap).edit? %>
                <%= link_to edit_scrap_path(@scrap) do %>
                  <i class="material-icons">edit</i>
                <% end %>
              <% end %>
              <% if policy(@scrap).destroy? %>
                <%= link_to scrap_path(@scrap),
                  method: :delete,
                  data: { confirm: "Are you certain?" } do %>
                  <i class="material-icons">delete_forever</i>
                <% end %>
              <% end %>

              <p class="subtitle">
                By 
                <%= link_to @scrap.user.name, @scrap.user, 
                  rel: "author", itemprop: "author" %>
              </p>
              <meta itemprop="description"
                    content="<%= @scrap.description %>" />
              <% unless @scrap.description.blank? %>
                <p><%= render_markdown @scrap.description %></p>
              <% end -%>

              <%= render "tags/tag_list",
                tags: @scrap.tags %>

              <%= time_tag @scrap.created_at, itemprop: "dateCreated" %>
          </div>
        </div>
      </div>
    </div>
  </div>


  <%= render partial: "comments/comment_section",
    locals: { comments: @scrap.comments, commentable: @scrap } %>
</div>