config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :users do
    member do
      get "artworks", to: "feeds#artworks", feed_type: :created
      get "artwork_reblogs", to: "feeds#artwork_reblogs", feed_type: :created
      get "scraps", to: "feeds#scraps", feed_type: :created
      get "verify_email"
      get "unsubscribe"
      get "followers"
      get "mutuals"
    end
  end


  resources :sessions do
    collection do
      delete "logout"
    end
  end

  concern :commentable do |options|
    resources :comments, options
  end

  resources :scraps do
    concerns :commentable, commentable_type: "Scrap"
  end

  resources :artworks do
    concerns :commentable, commentable_type: "Artwork"
  end

  resources :followings, only: [:create, :destroy]

  resources :tags

  resources :artwork_reblogs

  resources :notifications, only: [:index, :show, :update, :destroy] do
    get "unread", on: :collection
  end

  scope "feeds" do
    get "/", to: "feeds#index"
    get "artworks", to: "feeds#artworks"
    get "scraps", to: "feeds#scraps"
    get "artwork_reblogs", to: "feeds#artwork_reblogs"
  end

  scope "sitemaps", defaults: { format: "txt" } do
    get "tags", to: "sitemaps#tags"
    get "users", to: "sitemaps#users"
    get "scraps", to: "sitemaps#scraps"
    get "artworks", to: "sitemaps#artworks"
    get "/", to: "sitemaps#index"
  end

  get "faq", to: "info_pages#faq"
  get "rules", to: "info_pages#rules"
  get "legal", to: "info_pages#legal"

  root to: "home#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  def paginate collection
    c = if params["page_after"]
      collection.page_after(to_time(params["page_after"]))
    else
      collection.paginate_order
    end
    c.limit(per_page)
  end

  def per_page
    params["per_page"].try(:to_i) || 20
  end


  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def pundit_user
    @pundit_user ||= UserContext.new(current_user, user_prefs)
  end

  def user_prefs
    (session[:prefs] || {}).merge(params.permit(prefs: {})[:prefs] || {})
  end

  protected

  def to_time time
    Time.at(time.to_f)
  end

  helper_method :current_user
end

app/helpers/application_helper.rb
module ApplicationHelper

  def next_page collection
    np = params.permit(:per_page,
                       prefs: {},
                       search: {})
    min = collection.to_a.map(&:created_at).min.to_f
    url_for(np.merge(page_after: min))
  end

  def page_title title
    provide(:title) { title }
  end

  def yield_page_title
    if content_for?(:title) then 
      content_for(:title) + ' | '
    else 
      ""
    end
  end

  def meta_tag tag, text
    provide :"meta_#{tag}", text
  end

  def tags_to_keywords tags
    tags.pluck(:name).join(",")
  end

  def yield_meta_tag(tag, default_text="")
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end

  def og_tag(tag, text)
    provide :"og_#{tag}", text
  end

  def yield_og_tag(tag, default_text="")
    content_for?(:"og_#{tag}") ? content_for(:"og_#{tag}") : default_text
  end

  def render_markdown str
    (markdown_renderer.render str).html_safe
  end

  def default_meta_description
    %Q{ArtWorkDraft is a community of artists that's not run by a big corporation.
    It's the perfect place to post your paintings, drawings, fanart, and anything else you might create.}
  end

  protected

  def markdown_renderer
    @@markdown_renderer = 
      Redcarpet::Markdown.new(markdown_renderer_backend,
                              tables: true,
                              fenced_code_blocks: true,
                              autolink: true,
                              strikethrough: true,
                              superscript: true,
                              underline: true,
                              highlight: true,
                              footnotes: true)
  end

  def markdown_renderer_backend
    @@markdown_renderer_backend ||= 
      Redcarpet::Render::HTML.new(filter_html: true, safe_links_only: true)
  end
end

app/views/application/_flash_notify.html.erb
<% if flash.alert -%>
  <div class="notification is-danger is-button-notification">
    <button class="delete"></button>
    <%= flash.alert %>
  </div>
<% end -%>
<% if flash.notice -%>
  <div class="notification is-primary is-button-notification">
    <button class="delete"></button>
    <%= flash.notice %>
  </div>
<% end -%>

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="columns">
      <div class="column is-one-third"">
        <h1 class="title">ArtWorkDraft</h1>
        <h2 class="subtitle">
          An art community that's actually a community.
        </h2>
        <a href="https://www.github.com/anthonysuper/artworkdraft">
          Open Source
        </a>
      </div>
      <div class="column">
        <h2 class="subtitle">Navigation</h2>
        <ul>
          <li><a href="/users/new">Create Account</a></li>
          <li><a href="/artworks">Artworks</a></li>
          <li><a href="/scraps">Scraps</a></li>
          <li><a href="/users">Users</a></li>
        </ul>
      </div>
      <div class="column">
        <h2 class="subtitle">Creation</h2>
        <ul>
          <li><a href="/artworks/new">Upload Artwork</a></li>
          <li><a href="/scraps/new">Upload Scrap</a></li>
          <li><a href="/tags/new">Upload Tag</a></li>
        </ul>
      </div>
      <div class="column">
        <h2 class="subtitle">Information</h2>
        <ul>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/rules">Rules</a></li>
          <li><a href="/legal">Legal/TOS</a></li>
        </ul>
      </div>
    </div>
     <p>Copyright 2018 Noided Media</p>
  </div>
 
</footer>

app/views/application/_navbar.html.erb
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <p class="title">ArtWorkDraft</p>
    </a>
    <a role="button" data-target="navMenu"
      class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class="navbar-menu" id="navMenu">
    <div class="navbar-start">
      <% if current_user %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Create
          </a>

          <div class="navbar-dropdown">
            <%= link_to "Scrap", new_scrap_path, class: "navbar-item" %>
            <%= link_to "Artwork", new_artwork_path, class: "navbar-item" %>
            <%= link_to "Tag", new_tag_path, class: "navbar-item" %>
          </div>
        </div>

      <% end %>

    </div>

    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Browse
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Users", users_path, class: "navbar-item" %>
          <%= link_to "Scraps", scraps_path, class: "navbar-item" %>
          <%= link_to "Artworks", artworks_path, class: "navbar-item" %>
          <%= link_to "Tags", tags_path, class: "navbar-item" %>
        </div>
      </div>

      <% if current_user %>
        <div class="navbar-item has-dropdown"
             data-vue-component="notifications/root"
             data-notification-count="<%= current_user.notifications.unread.count %>">
          <a class="navbar-link is-arrowless">
            <i class="material-icons notification-icon"
               data-notification-count="<%= current_user.notifications.unread.count %>">
              notifications
            </i>
          </a>
          <div class="navbar-dropdown">
            <a class="navbar-item">
              Test
            </a>
          </div>
        </div>
        <%= link_to current_user.name, current_user, class: "navbar-item" %>
        <div class="navbar-item">
          <%= render "sessions/logout_form" %>
        </div>
      <% else %>
        <a class="navbar-item" href="/sessions/new">
          Login
        </a>
      <% end %>

    </div>
  </div>
  </div>
</nav>

app/views/application/_page_level.html.erb
<div class="level">
  <div class="level-left">
  </div>
  <div class="level-right">
    <div class="level-item">
      <%= link_to "Next page", next_page(collection), class: "button" %>
    </div>
  </div>
</div>